export interface Migration {
  version: number;
  statements: readonly string[];
}

export const migrations: readonly Migration[] = [
  {
    version: 1,
    statements: [
      "CREATE TABLE IF NOT EXISTS settings (owner_id TEXT PRIMARY KEY NOT NULL, theme TEXT NOT NULL DEFAULT 'system', reduce_motion INTEGER NOT NULL DEFAULT 0, editor_font_size INTEGER NOT NULL DEFAULT 17, trash_retention_days INTEGER NOT NULL DEFAULT 30)",
      "CREATE TABLE IF NOT EXISTS devices (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, platform TEXT NOT NULL, name TEXT NOT NULL, app_version TEXT NOT NULL, last_seen_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY NOT NULL, email TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS workspaces (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, created_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, kind TEXT NOT NULL, title TEXT NOT NULL, markdown TEXT NOT NULL, path TEXT, project_id TEXT, is_pinned INTEGER NOT NULL DEFAULT 0, revision INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT, updated_by_device_id TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS document_revisions (id TEXT PRIMARY KEY NOT NULL, document_id TEXT NOT NULL, revision INTEGER NOT NULL, markdown TEXT NOT NULL, created_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, canonical_document_id TEXT NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, priority TEXT NOT NULL, updated_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS versions (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, project_id TEXT NOT NULL, canonical_document_id TEXT NOT NULL, version TEXT NOT NULL, status TEXT NOT NULL, updated_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS tasks_index (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, document_id TEXT NOT NULL, text TEXT NOT NULL, completed INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS tags (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, name TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS project_tags (project_id TEXT NOT NULL, tag_id TEXT NOT NULL, PRIMARY KEY (project_id, tag_id))",
      "CREATE TABLE IF NOT EXISTS conflicts (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, base_revision INTEGER NOT NULL, local_revision INTEGER NOT NULL, remote_revision INTEGER NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)",
      "CREATE TABLE IF NOT EXISTS outbox (id TEXT PRIMARY KEY NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, operation TEXT NOT NULL, base_revision INTEGER NOT NULL, payload_version INTEGER NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, next_attempt_at TEXT, idempotency_key TEXT NOT NULL UNIQUE)",
      "CREATE TABLE IF NOT EXISTS sync_cursors (collection TEXT PRIMARY KEY NOT NULL, cursor TEXT)",
      "CREATE TABLE IF NOT EXISTS migrations (version INTEGER PRIMARY KEY NOT NULL, applied_at TEXT NOT NULL)",
    ],
  },
  {
    version: 2,
    statements: [
      "CREATE VIRTUAL TABLE IF NOT EXISTS documents_fts USING fts5(document_id UNINDEXED, owner_id UNINDEXED, title, markdown)",
      "INSERT INTO documents_fts (document_id, owner_id, title, markdown) SELECT d.id, d.owner_id, d.title, d.markdown FROM documents d WHERE d.deleted_at IS NULL AND NOT EXISTS (SELECT 1 FROM documents_fts f WHERE f.document_id = d.id)",
      "CREATE TABLE IF NOT EXISTS document_drafts (document_id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, markdown TEXT NOT NULL, updated_at TEXT NOT NULL, selection_from INTEGER NOT NULL DEFAULT 0, selection_to INTEGER NOT NULL DEFAULT 0)",
      "CREATE INDEX IF NOT EXISTS documents_owner_updated_idx ON documents (owner_id, deleted_at, updated_at DESC)",
      "CREATE INDEX IF NOT EXISTS document_revisions_document_idx ON document_revisions (document_id, revision DESC)",
    ],
  },
  {
    version: 3,
    statements: [
      "ALTER TABLE projects ADD COLUMN slug TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE projects ADD COLUMN tags TEXT NOT NULL DEFAULT '[]'",
      "ALTER TABLE projects ADD COLUMN target_date TEXT",
      "ALTER TABLE projects ADD COLUMN current_version TEXT",
      "ALTER TABLE projects ADD COLUMN next_version TEXT",
      "ALTER TABLE projects ADD COLUMN next_action TEXT",
      "ALTER TABLE projects ADD COLUMN repository_url TEXT",
      "ALTER TABLE projects ADD COLUMN platforms TEXT NOT NULL DEFAULT '[]'",
      "ALTER TABLE projects ADD COLUMN health TEXT NOT NULL DEFAULT 'good'",
      "ALTER TABLE projects ADD COLUMN revision INTEGER NOT NULL DEFAULT 1",
      "ALTER TABLE projects ADD COLUMN created_at TEXT",
      "ALTER TABLE projects ADD COLUMN deleted_at TEXT",
      "ALTER TABLE projects ADD COLUMN updated_by_device_id TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE versions ADD COLUMN target_date TEXT",
      "ALTER TABLE versions ADD COLUMN android_status TEXT NOT NULL DEFAULT 'not_planned'",
      "ALTER TABLE versions ADD COLUMN ios_status TEXT NOT NULL DEFAULT 'not_planned'",
      "ALTER TABLE versions ADD COLUMN completed_tasks INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE versions ADD COLUMN total_tasks INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE versions ADD COLUMN revision INTEGER NOT NULL DEFAULT 1",
      "ALTER TABLE versions ADD COLUMN created_at TEXT",
      "ALTER TABLE versions ADD COLUMN deleted_at TEXT",
      "ALTER TABLE versions ADD COLUMN updated_by_device_id TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE tasks_index ADD COLUMN project_id TEXT",
      "ALTER TABLE tasks_index ADD COLUMN version_id TEXT",
      "ALTER TABLE tasks_index ADD COLUMN line_anchor TEXT NOT NULL DEFAULT ''",
      "ALTER TABLE tasks_index ADD COLUMN priority TEXT",
      "ALTER TABLE tasks_index ADD COLUMN due_date TEXT",
      "ALTER TABLE tasks_index ADD COLUMN blocked INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE tasks_index ADD COLUMN blocker_text TEXT",
      "ALTER TABLE tasks_index ADD COLUMN canceled INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE tasks_index ADD COLUMN revision INTEGER NOT NULL DEFAULT 1",
      "CREATE TABLE IF NOT EXISTS project_blockers (id TEXT PRIMARY KEY NOT NULL, owner_id TEXT NOT NULL, project_id TEXT NOT NULL, task_id TEXT, text TEXT NOT NULL, resolved INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, resolved_at TEXT)",
      "CREATE INDEX IF NOT EXISTS projects_owner_updated_idx ON projects (owner_id, deleted_at, updated_at DESC)",
      "CREATE INDEX IF NOT EXISTS projects_owner_status_idx ON projects (owner_id, deleted_at, status)",
      "CREATE INDEX IF NOT EXISTS versions_project_updated_idx ON versions (owner_id, project_id, deleted_at, updated_at DESC)",
      "CREATE INDEX IF NOT EXISTS tasks_owner_due_idx ON tasks_index (owner_id, completed, canceled, due_date)",
      "CREATE INDEX IF NOT EXISTS tasks_project_idx ON tasks_index (owner_id, project_id, version_id)",
      "CREATE INDEX IF NOT EXISTS blockers_project_idx ON project_blockers (owner_id, project_id, resolved)",
    ],
  },
];
