import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

await build({
  entryPoints: ["src/web-entry.ts"],
  bundle: true,
  format: "iife",
  minify: true,
  outfile: "dist/editor-web.js",
  platform: "browser",
  sourcemap: false,
});

const bundle = await readFile("dist/editor-web.js", "utf8");
await mkdir("../../apps/mobile/src/editor", { recursive: true });
await writeFile(
  "../../apps/mobile/src/editor/editor-bundle.ts",
  `export const EDITOR_BUNDLE = ${JSON.stringify(bundle)} as const;\n`,
  "utf8",
);

// The WebView can't see fonts the app bundles natively, so Inter is inlined into the editor page.
// Only the Latin and Latin Extended subsets (English and Turkish) of the variable font are kept:
// one file per subset covers every weight the editor uses.
const require = createRequire(import.meta.url);
const interDir = dirname(require.resolve("@fontsource-variable/inter/package.json"));
const interCss = await readFile(join(interDir, "wght.css"), "utf8");
const faces = [];
for (const subset of ["latin-ext", "latin"]) {
  const block = interCss.match(
    new RegExp(`/\\* inter-${subset}-wght-normal \\*/\\s*(@font-face \\{[^}]*\\})`, "u"),
  )?.[1];
  if (!block) throw new Error(`Inter ${subset} face not found in @fontsource-variable/inter`);
  const file = await readFile(join(interDir, "files", `inter-${subset}-wght-normal.woff2`));
  faces.push(
    block
      .replace(
        /src: [^;]+;/u,
        `src: url(data:font/woff2;base64,${file.toString("base64")}) format('woff2');`,
      )
      .replace(/\s+/gu, " "),
  );
}
await writeFile(
  "../../apps/mobile/src/editor/editor-fonts.ts",
  `// Generated by packages/editor/scripts/build-web.mjs from @fontsource-variable/inter (OFL-1.1).\nexport const EDITOR_FONT_CSS = ${JSON.stringify(faces.join("\n"))};\n`,
  "utf8",
);
